# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NadoSunbae-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NadoSunbae-iOS
  pod 'Moya'
  pod 'SnapKit'
  pod 'Then'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SwiftyJSON'
  pod 'Firebase/Messaging'
end
